[package]
name = "otel-viewer"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
chrono = "0.4.45"
clap = { version = "4.6.7", features = ["derive"] }
duckdb = { version = "1.10505.0", features = ["bundled"] }
hex = "0.4.3"
mime_guess = "2.0.5"
prost = { version = "0.14.4", features = ["derive"] }
rand = "0.10.3"
rust-embed = "8.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
tokio-util = "0.7.19"
tonic = { version = "0.14.6", features = ["gzip"] }
tonic-prost = "0.14.6"
tonic-reflection = "0.14.6"
tower-http = { version = "0.7.1", features = ["cors"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dev-dependencies]
reqwest = { version = "0.13.5", features = ["json"] }

[build-dependencies]
protoc-bin-vendored = "3.2.0"
tonic-prost-build = "0.14.6"
